# Generated by Django 4.0.6 on 2022-07-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jugadores', '0002_jugador_apuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='apuestaAnt',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
