# Generated by Django 4.0.6 on 2022-07-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jugadores', '0003_jugador_apuestaant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='apuestaAnt',
            new_name='apuestaCant',
        ),
    ]
